config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  resources :articles do
  	resources :comments
  end
  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  	@article = Article.new
  end
  
  def index
  	@articles = Article.all(:order => "created_at DESC")
  	@posts = Article.includes(:comments).order("created_at DESC").limit(3)
  end
  
  def create
  	@article = Article.new(article_params)
  	
  	if @article.save
  		redirect_to @article
  	else
  		render 'new'
  	end
  end
  
  def show
  	@article = Article.find(params[:id])
  end
  
  def edit
  	@article = Article.find(params[:id])
  end
  
  def update
  	@article = Article.find(params[:id])
  	
  	if @article.update(article_params)
  		redirect_to @article
  	else
  		render 'edit'
  	end
  end	
  
  def destroy
  	@article = Article.find(params[:id])
  	@article.destroy
  	
  	redirect_to articles_path
  end
  
  
  private
  	def article_params
  		params.require(:article).permit(:title, :text)
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end
	
	private 
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<% if @article.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@article.errors.count, "error") %>: Tiêu đề bài viết quá ngắn!</h2>
		<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
	<% end %>
	
	<p>
		<%= f.label :title, "Tiêu đề" %><br>
		<%= f.text_field :title, :class => 'form-control', :placeholder => "Tiêu đề bài viết" %>
	</p>
	
	<p>
		<%= f.label :text, "Nội dung" %><br>
		<%= f.text_area :text, :class => 'form-control', :placeholder => "Nội dung bài viết" %>
	</p>
	
	<p>
		<%= f.submit "Đăng bài viết", :class => "btn btn-primary" %>
	</p>
<% end %>

app/views/articles/_maincontent.html.erb
<div class="mainContent">
	<div class="content">
	<% @articles.each do |article| %>
		<article class="topcontent">
			<header>
				<h2>
					<a href="<%= article_path(article) %>" rel="bookmark" title="Permalink to <%= article.title %>"><%= article.title %></a>
				</h2>
			</header>
			
			<footer>
				<p class="post-info">
					<img src="/assets/ico-cal.gif"> <%= article.created_at.to_s(:long) %> &nbsp;
					
					<span><img src="/assets/ico-com.gif"> <%= article.comments.count %> bình luận</span>
				</p>
			</footer>
			
			<div class="detailContent">
				<p><%= simple_format(article.text) %></p>
			</div>
		</article>
	<% end %>
	</div>
	
		<%= render 'sidebar' %>
</div> <!-- end mainContent -->

app/views/articles/_navigationbar.html.erb
<header class="mainHeader">
	<img src="/assets/tuongnguyen.jpg">
	<nav>
		<ul>
			<li <%= yield(:active_home) %> ><a href="<%= welcome_index_path %>">Trang chủ</a></li>
			<li <%= yield(:active_about) %> ><a href="<%= welcome_about_path %>">Giới thiệu</a></li>
			<li <%= yield(:active_blog) %> ><a href="<%= articles_path %>">Blog</a></li>
			<li <%= yield(:active_contact) %> ><a href="<%= welcome_contact_path %>">Liên hệ</a></li>
		</ul>
	</nav>
</header>

app/views/articles/_postdetail.html.erb
<article>
			<header>
				<h1>
					<a href="<%= article_path(@article) %>" rel="bookmark" title="Permalink to <%= @article.title %>"><%= @article.title %></a>
				</h1>
			</header>
			
			<footer>
				<p class="post-info">Được viết bởi 
					<span><img src="/assets/authorz.png"> Tường Trọng Nguyễn</span> &nbsp; 
					<img src="/assets/ico-cal.gif"> <%= @article.created_at.to_s(:long) %> &nbsp; 
					<span><img src="/assets/ico-com.gif"> <%= link_to " #{@article.comments.count} bình luận »", :anchor => "comments_content" %></span>
				</p>
			</footer>
			
			<div class="detailContent">
				<p><%= simple_format(@article.text) %></p>
			</div>
</article>

app/views/articles/_sidebar.html.erb
<aside class="top-sidebar">
	<article>
		<h2>Bài viết mới nhất</h2>	
		<% @posts.each do |post| %>
      <p><a href="<%= article_path(post) %>" rel="bookmark" title="Permalink to <%= post.title %>"><%= post.title %></a></p>
      <hr>
		<% end %>
	</article>
</aside>
		
<aside class="middle-sidebar">
	<article>
		<h2>Xem nhiều nhất</h2>
		<p>Đây là phần dành cho bài viết được xem nhiều nhất, nội dung sẽ được thêm sau.</p>
	</article>
</aside>
		
<aside class="bottom-sidebar">
	<article>
		<h2>Thể loại</h2>
		<p>Đây là phần dành cho thể loại bài viết, nội dung sẽ được thêm sau.</p>
	</article>
</aside>

app/views/articles/edit.html.erb
<% provide(:active_blog, "class=active") %>


<h1>Chỉnh sửa bài viết</h1>

<%= render 'form' %>

<%= link_to 'Quay lại', articles_path %>

app/views/articles/index.html.erb
<% provide(:active_blog, "class=active") %>

<h1>Tất cả các bài viết đều nằm ở đây</h1>

<%= link_to 'Viết bài mới', new_article_path %>

<%= render "maincontent" %>

<%= render "welcome/mainFooter" %>

app/views/articles/new.html.erb
<% provide(:active_blog, "class=active") %>


<h1>Viết bài mới</h1>

<%= render 'form' %>

<%= link_to 'Quay lại', articles_path %>

app/views/articles/show.html.erb
<% provide(:active_blog, "class=active") %>


<div class="topcontent">
	<!-- post detail -->
	<%= render 'postdetail' %>


	<!-- comments content -->
	<h2 id="header_comments">Ý kiến bạn đọc</h2>
	<%= render @article.comments %>

	<!-- comments form -->
	<%= render "comments/form" %>

	<%= link_to 'Quay lại', articles_path %>
	| <%= link_to 'Chỉnh sửa', edit_article_path(@article) %>
</div>

<%= render "welcome/mainFooter" %>

app/views/comments/_comment.html.erb
<p id="comments_content">
	<%= comment.body %><br>
	<strong><%= comment.commenter %></strong> - <span><%= comment.created_at.to_s(:long) %></span>
</p>		

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
<div class="comments_form">
	<p>
		<%= f.label :commenter, "Tên:" %><br>
		<%= f.text_field :commenter, :class => 'form-control', :placeholder => "Họ và tên" %>
	</p>
	
	<p>
		<%= f.label :body, "Nội dung bình luận:" %><br>
		<%= f.text_area :body,  :class => 'form-control', :placeholder => "Ý kiến của bạn" %>
	</p>
	
	<p>
		<%= f.submit "Đăng bình luận", :class => "btn btn-danger", :id => "submit_comments" %>
	</p>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Rails Tutorial</a>
		by Michael Hartl
	</small> 
	<nav>
		<ul>
			<li><%= link_to "About", '#' %></li>
			<li><%= link_to "Contact", '#' %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "sample app", '#', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", '#' %></li>
					<li><%= link_to "Help", '#' %></li>
					<li><%= link_to "Sign in", '#' %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tường Nguyễn Blog</title>
  <link rel="icon" href="/assets/tuongicon.ico" type="image/x-icon">
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="body">
<!-- header -->
<%= render 'articles/navigationbar' %>

<!-- body -->
<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	is a project to make a book and screencasts to teach web development with <a href="http://rubyonrails.org/">Ruby on Rails</a>. this is the sample application for the turorial.
</p>
	

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact me at phone number: 01654171471 or email: nguyenpeter.edu@gmail.com<br />
	Contact Ruby on Rails Tutorial about the sample app at the 
	<a href="http://railstutorial.org/contact">contact page</a>
</p>
	

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	Get help on the Ruby on Rails Tutorial at the 
	<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
	To get help on this sample app, see the 
	<a href="http://railstutorial.org/book">Rails tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to the Sample App</h1>

	<h2>
		This is the home page for the 
		<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
		sample application.
	</h2>

	<%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/welcome/_mainFooter.html.erb
<footer class="footer">
  <small>
    Copyright © 2014 <a href="<%= welcome_index_path %>">Tường Nguyễn Blog</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Giới thiệu",    welcome_about_path %></li>
      <li><%= link_to "Liên Hệ", welcome_contact_path %></li>
      <li><%= link_to "Blog", articles_path %></li>
      <li><a href="#">Đăng nhập</a></li>
    </ul>
  </nav>
</footer>

app/views/welcome/about.html.erb
<% provide(:active_about, 'class=active') %>
<% provide(:welcome_background, 'class=welcome_bg') %>

<div class="center">
	<div class="center hero-unit" >
		<h1>Giới thiệu</h1>
		<p>
		  Tường Nguyễn Blog là một blog chuyên về chia sẻ kinh nghiệm, ý tưởng hay. Blog được thành lập vào ngày 1/6/2014 với chủ nhân chính là Tường Trọng Nguyễn sinh năm 1993 và hiện đang sống và làm việc tại thành phố Hồ Chí Minh.
  	</p>
  	<p>
  		Blog này chỉ tập trung mạnh nhất vào những ý tưởng hay, thiết thực như quản lý thời gian, phát triển bản thân,... Tuy nhiên vẫn mở rộng ra thêm nhiều lĩnh vực khác như học tập, lập trình, các vấn đề tin học, ...
  	</p>
  	<p>
  		Các bài viết trên đây mang ý kiến và cách nhìn chủ quan được viết bởi Tường Trọng Nguyễn thông qua kinh nghiệm cá nhân, học hỏi và sưu tầm từ nhiều nguồn khác nhau.
  	</p>
	</div>
</div>

<%= render "welcome/mainFooter" %>

app/views/welcome/contact.html.erb
<% provide(:active_contact, 'class=active') %>
<% provide(:welcome_background, 'class=welcome_bg') %>

<div class="center">
	<div class="center hero-unit" >
		<h1>Liên hệ</h1>
		<p>
		  Bạn muốn liên hệ với Tường Nguyễn Blog? Dĩ nhiên, bạn có thể vì Tường Nguyễn Blog luôn sẵn sàng lắng nghe và trao đổi cùng bạn. Các bạn có thể liên hệ với mình qua email: nguyentrongtuong1993@yahoo.com hoặc <a href="https://www.facebook.com/nguyentrongtuong1993" target="_blank">facebook</a>
  	</p>
  	<p>
  		Trong lúc đọc bài và gặp thắc mắc, Tường Nguyễn Blog khuyến khích bạn để lại comment trong bài viết đó để nhiều người cùng xem và thảo luận.
  	</p>
	</div>
</div>

<%= render "welcome/mainFooter" %>

app/views/welcome/index.html.erb
<% provide(:active_home, 'class=active') %>
<% provide(:welcome_background, 'class=welcome_bg') %>

<div class="center">
	<div class="center hero-unit" >
		<h1>Welcome to Tường Nguyễn Blog!</h1>
		<h2>
		  Nơi chia sẻ những ý tưởng hay học hỏi được và kinh nghiệm cá nhân khi áp dụng chúng.
  	</h2>
		<a href="<%= articles_path %>" class="btn btn-large btn-primary" id="blogButton" >Tường Nguyễn Blog</a>
	</div>
</div>

<%= render "welcome/mainFooter" %>